### ISSUE TITLE
Custom health checks

### ISSUE THREAD

**Issue by simplelife2010** [balena-io/device-diagnostics#157]
Would it be possible to allow the deployment of customer-provided health checks (based on shell scripts)? These could be defined on application level. The results should be visible in balenaCloud.

**Comment by xginn8** [comment]
Hi @simplelife2010,

This feature has now made it into balenaCloud. You can use the Docker Healthcheck directive to implement health checks in your app. See https://github.com/balena-io/device-diagnostics/blob/master/diagnostics.md#check_user_services for more information.
