### ISSUE TITLE
[jetson-nano] check_temperature shows the dummy value of 100 degrees

### ISSUE THREAD

**Issue by gelbal** [balena-io/device-diagnostics#168]
Diagnostics on Jetson Nano always shows 100°C as the underlying software cannot read PMIC temperature.

Relevant threads from NVDIA website:
https://devtalk.nvidia.com/default/topic/1069388/jetson-agx-xavier/pmic-temperatures-of-100-degrees-celsius/post/5417171/#5417171
https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3231/index.html#page/Tegra%2520Linux%2520Driver%2520Package%2520Development%2520Guide%2Fpower_management_nano.html%23wwpID0E0BG0HA

**Comment by xginn8** [comment]
This fix has been rolled out.
