### ISSUE TITLE
Add detection of over-temperature events.

### ISSUE THREAD

**Issue by jimsynz** [balena-io/device-diagnostics#183]
It'd be awesome if events like this (seen on a customer's NUC):

```
[1731237.213211] mce: CPU0: Core temperature above threshold, cpu clock throttled (total events = 13557)
```

Were somehow surfaced in the checks in the UI.

**Comment by xginn8** [comment]
We do already check any onboard sensors, but this source of data is probably more robust (as each device carries it's own threshold).

**Comment by saintaardvark** [comment]
See also #209.

**Comment by xginn8** [comment]
This is now in prod

**Comment by xginn8** [comment]
It was all @saintaardvark
