### ISSUE TITLE
The tool reports errors for Intel Edison boards and block devices with no child partitions

### ISSUE THREAD

**Issue by roman-mazur** [balena-io/device-diagnostics#184]
## Steps to Reproduce the Problem

- Open the health checks page on the balenaCloud dashboard for an Edison board running balena OS 2.9
- See the message
```
Error reported when querying checks data: checks failed: exit code 2 stderr: curl: option --retry-connrefused: is unknown curl: try 'curl --help' or 'curl --manual' for more information jq: Unknown option -cn Use jq --help for help with command-line options, or see the jq documentation at http://stedolan.github.com/jq jq: Unknown option -cn Use jq --help for help with command-line options, or see the jq documentation at http://stedolan.github.com/jq cat: /sys/class/thermal/thermal_zone0/temp: In
```
- With balena OS `balenaOS 2.31.5+rev1`, the checks can be run, but the dashboard will display the following error on top of the results:
```
Error reported when querying checks data: jq: error (at <stdin>:21): Cannot iterate over null (null)
```

## Specifications

- balenaOS: balenaOS 2.31.5+rev1
- Device type: Intel Edison
- Supervisor: 9.11.3

**Comment by xginn8** [comment]
We decided in https://github.com/balena-io/device-diagnostics/issues/126 to limit support of checks to devices that are multicontainer-capable.

I have opened https://github.com/balena-io/device-diagnostics/pull/185 to sort the other error.

**Comment by roman-mazur** [comment]
Thanks, makes sense.

**Comment by xginn8** [comment]
This fix has been deployed.
