### ISSUE TITLE
Tuning image corruption timeouts

### ISSUE THREAD

**Issue by xginn8** [balena-io/device-diagnostics#203]
Collecting timeout data here for tuning

**Comment by ntzovanis** [comment]
[This device](https://dashboard.balena-cloud.com/devices/d713fa2f59f835c94d6bd69c76a49737/summary) in [this thread](https://jel.ly.fish/c7eb4bfb-3e34-4fc9-8cbf-f79edd725a7f) is reporting a timeout in check_image_corruption.

**Comment by ntzovanis** [comment]
[This device](https://dashboard.balena-cloud.com/devices/de16851e66820403c2e27712a180d90c/summary) in [this thread](https://jel.ly.fish/ede9c5fb-d08c-44cd-bba6-425438c5d948) too.

**Comment by xginn8** [comment]
running each failure with a 60s timeout to gather some better data:

`for i in ${imgs}; do balena images | grep $i | awk '{print $NF}' && timeout 60 time balena save $i > /dev/null || echo timed out; done; cat /etc/os-release`

**Comment by xginn8** [comment]
> [This device](https://dashboard.balena-cloud.com/devices/de16851e66820403c2e27712a180d90c/summary) in [this thread](https://jel.ly.fish/ede9c5fb-d08c-44cd-bba6-425438c5d948) too.

results:

```
907MB
timed out
160MB
real    0m 55.10s
user    0m 0.45s
sys     0m 0.82s
125MB
real    0m 39.24s
user    0m 0.44s
sys     0m 0.54s
55.5MB
real    0m 21.50s
user    0m 0.30s
sys     0m 0.21s
ID="balena-os"
NAME="balenaOS"
VERSION="2.48.0+rev1"
VERSION_ID="2.48.0+rev1"
PRETTY_NAME="balenaOS 2.48.0+rev1"
MACHINE="fincm3"
VARIANT="Development"
VARIANT_ID="dev"
META_BALENA_VERSION="2.48.0"
RESIN_BOARD_REV="54d3ae9"
META_RESIN_REV="19c838a"
SLUG="fincm3"
```

**Comment by xginn8** [comment]
> [This device](https://dashboard.balena-cloud.com/devices/d713fa2f59f835c94d6bd69c76a49737/summary) in [this thread](https://jel.ly.fish/c7eb4bfb-3e34-4fc9-8cbf-f79edd725a7f) is reporting a timeout in check_image_corruption.

results:

```
113MB
real    0m 24.19s
user    0m 0.31s
sys     0m 0.33s
1.9GB
timed out
55.5MB
real    0m 18.64s
user    0m 0.23s
sys     0m 0.21s
534MB
timed out
662MB
timed out
ID="balena-os"
NAME="balenaOS"
VERSION="2.46.1+rev1"
VERSION_ID="2.46.1+rev1"
PRETTY_NAME="balenaOS 2.46.1+rev1"
MACHINE="raspberrypi3"
VARIANT="Development"
VARIANT_ID="dev"
META_BALENA_VERSION="2.46.1"
RESIN_BOARD_REV="e194600"
META_RESIN_REV="f2295d2"
SLUG="raspberrypi3"
```

**Comment by xginn8** [comment]
> [sradevski] This issue has attached support thread https://jel.ly.fish/#/22de9426-f0fd-4dfa-9614-a16abcc35ebf

this device noted a slow sd card generally as well:

```
170MB
real 0m 57.14s
user    0m 0.43s
sys     0m 0.52s
55.5MB
real    0m 7.96s
user    0m 0.25s
sys     0m 0.18s
249MB
timed out
ID="balena-os"
NAME="balenaOS"
VERSION="2.47.0+rev1"
VERSION_ID="2.47.0+rev1"
PRETTY_NAME="balenaOS 2.47.0+rev1"
MACHINE="raspberrypi3"
VARIANT="Production"
VARIANT_ID="prod"
META_BALENA_VERSION="2.47.0"
RESIN_BOARD_REV="a08e3d7"
META_RESIN_REV="8b48eee"
SLUG="raspberrypi3"
```

**Comment by anujdeshpande** [comment]
[This](https://jel.ly.fish/c2137a37-baa4-4532-9561-233987abf8ea) device is showing the same issue

**Comment by xginn8** [comment]
> [This](https://jel.ly.fish/c2137a37-baa4-4532-9561-233987abf8ea) device is showing the same issue
> 
> ```
> root@71b132b:~# for i in ${imgs}; do balena images | grep $i | awk '{print $NF}' && timeout 60 time balena save $i > /dev/null || echo timed out; done; cat /etc/os-release
> ID="balena-os"
> NAME="balenaOS"
> VERSION="2.32.0+rev1"
> VERSION_ID="2.32.0"
> PRETTY_NAME="balenaOS 2.32.0+rev1"
> MACHINE="raspberrypi"
> VARIANT="Production"
> VARIANT_ID="prod"
> RESIN_BOARD_REV="11f5617"
> META_RESIN_REV="d0f6b80"
> SLUG="raspberry-pi"
> ```

In this device:

```
balena images | grep $i | awk '{print $NF}' && timeout 60 time balena save $i > /dev/null || echo timed out
58.9MB
real    0m 42.03s
user    0m 1.37s
sys     0m 1.91s
```

**Comment by gelbal** [comment]
Logs from [this device](https://dashboard.balena-cloud.com/devices/9580fb3b6ee5cd4e8c7d6a5e366fc2d1/summary) from [the thread](https://jel.ly.fish/4920e775-659b-40d9-bc1c-6555d7e599f0)

```
271MB
real    0m 8.01s
user    0m 0.20s
sys     0m 0.41s
ID="balena-os"
NAME="balenaOS"
VERSION="2.47.1+rev1"
VERSION_ID="2.47.1+rev1"
PRETTY_NAME="balenaOS 2.47.1+rev1"
MACHINE="genericx86-64"
VARIANT="Production"
VARIANT_ID="prod"
META_BALENA_VERSION="2.47.1"
RESIN_BOARD_REV="ff06ab6"
META_RESIN_REV="c6a9c94"
SLUG="intel-nuc"
```

**Comment by samothx** [comment]
I have a device that is showing the issue: https://dashboard.balena-cloud.com/devices/fd43346192ee5aa48159bb43e2b4b682 . Any hints on what this actually means ? Is it just a malfunction of the check ? Connected to SD-card speed ? Is there a workaround to ensure  images are  not corrupted ?

**Comment by xginn8** [comment]
> I have a device that is showing the issue: https://dashboard.balena-cloud.com/devices/fd43346192ee5aa48159bb43e2b4b682 . Any hints on what this actually means ? Is it just a malfunction of the check ? Connected to SD-card speed ? Is there a workaround to ensure images are not corrupted ?

It is a function of the SD card specs and the image size. If you see a message about corruption, it is safe to say those layers/images have issues. If you merely see a timeout message, it is best to run the command above (with an extended timeout) to gather more data and test.

For that device specifically, here is the output:

```
55.5MB
real    0m 14.20s
user    0m 0.43s
sys     0m 0.40s
857MB
timed out
ID="balena-os"
NAME="balenaOS"
VERSION="2.47.0+rev1"
VERSION_ID="2.47.0+rev1"
PRETTY_NAME="balenaOS 2.47.0+rev1"
MACHINE="raspberrypi3"
VARIANT="Production"
VARIANT_ID="prod"
META_BALENA_VERSION="2.47.0"
RESIN_BOARD_REV="a08e3d7"
META_RESIN_REV="8b48eee"
SLUG="raspberrypi3"
```

**Comment by xginn8** [comment]
More data:

```
53.5MB
real    0m 36.90s
user    0m 0.82s
sys     0m 1.37s
355MB
real    4m 4.67s
user    0m 4.18s
sys     0m 9.04s
ID="balena-os"
NAME="balenaOS"
VERSION="2.29.2+rev3"
VERSION_ID="2.29.2"
PRETTY_NAME="balenaOS 2.29.2+rev3"
RESIN_BOARD_REV="b6f570c"
META_RESIN_REV="22fffcd"
SLUG="beaglebone-black"
MACHINE="beaglebone"
VARIANT="Production"
VARIANT_ID="prod"
```

**Comment by saintaardvark** [comment]
The device in [this thread](https://jel.ly.fish/b2a23fc4-12ff-4dbc-ad03-7580c72ac67c):
```
root@fd43346:~# imgs=76fd2be95b74; for i in ${imgs}; do balena images | grep $i | awk '{print $NF}' && timeout 60 time balena save $i > /dev/null || echo timed out; done; cat /etc/os-release
55.5MB
real    0m 15.85s
user    0m 0.37s
sys     0m 0.40s
ID="balena-os"
NAME="balenaOS"
VERSION="2.47.0+rev1"
VERSION_ID="2.47.0+rev1"
PRETTY_NAME="balenaOS 2.47.0+rev1"
MACHINE="raspberrypi3"
VARIANT="Production"
VARIANT_ID="prod"
META_BALENA_VERSION="2.47.0"
RESIN_BOARD_REV="a08e3d7"
META_RESIN_REV="8b48eee"
SLUG="raspberrypi3"
```

**Comment by alexgg** [comment]
The RaspberryPi4 that I use for development is recently showing this issue. I have a Sandisk Extreme Pro SD card and I don't remember seeing this in the past.
```
real    0m 22.40s
user    0m 0.28s
sys     0m 0.68s
72.8MB
real    0m 8.28s
user    0m 0.11s
sys     0m 0.20s
224MB
real    0m 26.54s
user    0m 0.31s
sys     0m 0.88s
ID="balena-os"
NAME="balenaOS"
VERSION="2.48.0+rev5"
VERSION_ID="2.48.0+rev5"
PRETTY_NAME="balenaOS 2.48.0+rev5"
MACHINE="raspberrypi4-64"
VARIANT="Development"
VARIANT_ID="dev"
META_BALENA_VERSION="2.49.0"
RESIN_BOARD_REV="ca89c69235fe"
META_RESIN_REV="2d3fb7500dde"
SLUG="raspberrypi4-64"
```

**Comment by CameronDiver** [comment]
Device in this thread: https://jel.ly.fish/6e7a717d-bfc6-4959-a526-f098d6141992

**Comment by alanb128** [comment]
The device in [this thread](https://jel.ly.fish/view-all-support-threads/support-thread-1-0-0-front-cnv-7iknxvx):
```
root@a4afa40:~# imgs=3977c88a7059; for i in ${imgs}; do balena images | grep $i | awk '{print $NF}' && timeout 60 time balena save $i > /dev/null || echo timed out; done; cat /etc/os-release
53.8MB
real    0m 10.84s
user    0m 0.40s
sys     0m 0.15s
ID="balena-os"
NAME="balenaOS"
VERSION="2.38.0+rev1"
VERSION_ID="2.38.0+rev1"
PRETTY_NAME="balenaOS 2.38.0+rev1"
MACHINE="raspberrypi3"
VARIANT="Production"
VARIANT_ID="prod"
META_BALENA_VERSION="2.38.0"
RESIN_BOARD_REV="64eddd0"
META_RESIN_REV="b51e135"
SLUG="raspberrypi3"
```

**Comment by saintaardvark** [comment]
For now, this check has been removed with #220, as it is too noisy in its current form.  We may revisit this in the future.
