### ISSUE TITLE
Utilize RPi throttled state to provide more information

### ISSUE THREAD

**Issue by chrisys** [balena-io/device-diagnostics#209]
In [this issue](https://github.com/balenalabs/rosetta-at-home/issues/47) @ptrm highlights how the Pi VideoCore GPU can be polled to get the status of certain flags, see 'get_throttled' on this page: https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md

Could this be a more reliable way of obtaining status information when compared to looking at kernel error logs?

**Comment by chrisys** [comment]
Related: https://github.com/balena-os/balena-raspberrypi/issues/485

**Comment by saintaardvark** [comment]
[This comment](https://github.com/balenalabs/rosetta-at-home/issues/47#issuecomment-625810294) has some nice CLI math to parse the output of `vcgencmd get_throttled`.

**Comment by saintaardvark** [comment]
Closed via https://github.com/balena-io/device-diagnostics/pull/221.
