### ISSUE TITLE
Timeout 'command not found' error message produced by diagnose.sh

### ISSUE THREAD

**Issue by markcorbinuk** [balena-io/device-diagnostics#234]
When running 'Device Diagnostics' from the dashboard the standard error output displays the following:
```bash: line 27: timeout -v 1: command not found```

This is due to the following line in diagnose.sh:
```if "${TIMEOUT_VERBOSE}" echo > /dev/null ; then```

My suggested change is as follows:
```if ${TIMEOUT_VERBOSE} echo > /dev/null 2>&1; then```

Removing the double quotes solves the problem and adding the stderr redirect hides error messages for cases where the '-v' option is not supported.

This issue was produced when running diagnose 4.20.2.

**Comment by xginn8** [comment]
Thanks for reporting this! PRs welcome as always.
