### ISSUE TITLE
Diagnostics scripts crashes when control characters are returned from the healthcheck of a service

### ISSUE THREAD

**Issue by CameronDiver** [balena-io/device-diagnostics#246]
## Expected Behavior
We surface the HTTP return code or some other success indication and perhaps ignore the output?

## Actual Behavior
The output causes the diagnostics scripts to crash

## Steps to Reproduce the Problem

1. Return a body with control characters (for example newlines) from a service healthcheck and run the diagnostics checks from the dashboard
1.
1.

## References

https://jel.ly.fish/9a844337-4025-4402-a07d-32efd3fdfea4
---

**Comment by xginn8** [comment]
This work is now complete & deployed in production.
