### ISSUE TITLE
check_networking: test_balena_registry false positive for balenaOS >v2.53.1

### ISSUE THREAD

**Issue by saintaardvark** [balena-io/device-diagnostics#249]
Starting with balenaOS v2.53.1, the `test_balena_registry` check is failing with this error:  `Some networking issues detected: test_balena_registry: Could not communicate with  for authentication`.  Note the space between "with" and "for" -- that's because the `REGISTRY_ENDPOINT` variable used [here](https://github.com/balena-io/device-diagnostics/blob/master/scripts/checks.sh#L130-L139) is not being set.

Running `checks.sh` on the device with the `-x` flag showed this:

```
++++ test_balena_registry
++++ timeout --kill-after=20 10 balena login '' -u [redacted] --password [redacted]
++++ echo 'test_balena_registry: Could not communicate with  for authentication'
++++ timeout --kill-after=20 10 balena logout ''
+++ cmd_out='test_balena_registry: Could not communicate with  for authentication'
+++ '[' -n 'test_balena_registry: Could not communicate with  for authentication' ']'
++++ printf %s 'test_balena_registry: Could not communicate with  for authentication'
```

Again, note that the endpoint is not being specified; without this, we attempt to log into the Docker registry instead.  I confirmed this by re-running the command with the registry specified (`balena login registry2.balena-devices.com ...`), and that did work as expected.

This check *does* work on (at least) balenaOS 2.48.  Digging into it, it looks like we're sourcing variables in `checks.sh` from three places: /etc/profile, /usr/sbin/resin-vars, and /etc/os-release.  On a 2.48 device, resin-vars sets the `REGISTRY_ENDPOINT` variable; on a 2.54.2 device, it does not.  

Looking at the history in meta-balena, it looks like setting  `REGISTRY_ENDPOINT` was removed [here](https://github.com/balena-os/meta-balena/commit/b3222e619bbeebc0a2bd9e7419a9d8ae12b34dce#diff-3f6d33eb2637b5dbf9ae2030cb018e2d) as part of a number of unused config.json keys.

I assume that we won't be reverting this change.  Therefore, I think we'll need to have a default for this variable in this script to cover cases where it's not set.  However, if there's a better approach, I'm all ears.  In the meantime, I'll let support know that this check will be giving false alarms on newer versions of balenaOS.

**Comment by xginn8** [comment]
This can and should be sourced from the caller in the proxy, see https://github.com/balena-os/balenahup/blob/9f119d4c58f4de0ef8ffc38151f7eddbb81169cb/upgrade-2.x.sh#L844-L850 and https://github.com/balena-io/balena-proxy/blob/e5219ed77033d44cc4c581ac47373cebd044a34d/src/services/actions-backend/app.ts#L190-L211

**Comment by saintaardvark** [comment]
Re-opening this as it's not yet deployed.

**Comment by saintaardvark** [comment]
Deployed in prod and working. :tada:
